config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get "/resume", to: "home#resume"
  get "/adventures", to: "home#adventures"
  get "/projects", to: "home#projects"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end 

    def resume 
        pdf_filename = File.join(Rails.root, "public/cv.pdf")
        send_file(pdf_filename, :type => 'application/pdf', :disposition => 'inline')
    end 

    def adventures
    end 

    def projects
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class"container-fluid" style="background-color: #191923;">
  <div class="container py-3" style="max-width: 1620px;">

    <div class="row">
      <%= render "layouts/nav/sidebar" %>
      
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" >
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm" style="background-color: #191923; color: white">
              <div class="card-body">
                <img src="<%= image_path('motto.jpg') %>" style="width: 100%; height: 50%;"/>

                <div class="d-flex justify-content-between my-4" style="color: #FFC107">
                  <p>4 Projects </p>
                  <p>4 Happy Clients </p>
                  <p>4 years </p>
                </div>

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" >
                  <div class="col" >
                    <%= link_to resume_path, target: :_blank  do %>
                      <div class="card shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Resume" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#FFC107" dy=".3em">Resume</text><a xlink:href="www.medium.com/p/f254e0f6b71a" target="__blank"></a></svg>
                      </div>
                    <%end%>
                  </div>
                  <div class="col">
                    <%= link_to projects_path do %>
                      <div class="card shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Projects" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#FFC107" dy=".3em">Projects</text></svg>
                      </div>
                    <%end%>
                  </div>
                  <div class="col">
                    <%= link_to adventures_path do %>
                      <div class="card shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Adventures" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#FFC107" dy=".3em">Adventures</text></svg>
                      </div>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>

      

app/views/home/projects.html.erb
<div class"container-fluid" style="background-color: #191923;">
  <div class="container py-3" style="max-width: 1620px;">

    <div class="row">
      <%= render "layouts/nav/sidebar" %>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="color: white" >
        <div class="card mb-4 rounded-3 shadow-sm" style="background-color: #191923; color: white">
            <div class="card-body">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
                    <div class="col">
                        <div class="card shadow-sm px-4 py-4 mx-4 my-4" style="background-color: #55595c;">
                            <p>Project: https://www.conx.co</p>
                            <p>Category: Search Jobs in construction platform</p>
                            <p>Technology Used: Ruby on Rails, jQuery, APIs</p>
                        </div>
                    </div>
                    
                    <div class="col">
                        <div class="card shadow-sm px-4 py-4 mx-4 my-4" style="background-color: #55595c;">
                            <p>Project: https://apps.shopify.com/japan-order-csv</p>
                            <p>Category: Data formatter for Japan logistics</p>
                            <p>Technology Used: Ruby on Rails, ReactJS, GraphQL</p>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="card-body">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
                    <div class="col">
                        <div class="card shadow-sm px-4 py-4 mx-4 my-4" style="background-color: #55595c;">
                            <p>Project: www.app.shiftcare.com</p>
                            <p>Category: Schedule shift</p>
                            <p>Technology Used: Ruby on Rails, CoffeeScript</p>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm px-4 py-4 mx-4 my-4" style="background-color: #55595c;">
                            <p>Project: https://www.camplify.com.au/</p>
                            <p>Category: Search an RV</p>
                            <p>Technology Used: Ruby on Rails, ReactJS, Redis, Elasticsearch</p>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
      </main>
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalWebsiteRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
    <%= render "layouts/nav/footer" %> 
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  </body>

</html>

app/views/layouts/nav/_footer.html.erb
<div class="" style="background-color: #55595c">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-5" style="background-color: #55595c">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

app/views/layouts/nav/_header.html.erb
<div class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <header class="d-flex justify-content-center">
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Resume</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Projects</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Adventures</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
    </header>
</div>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="color: white;" >
  <div class="position-sticky pt-3 sidebar-sticky" >
    <div class="card" style="background: linear-gradient(159deg, rgba(37, 37, 50, 0.98) 0%, rgba(35, 35, 45, 0.98) 100%);">
      <div class="card-body">
        <img src="<%= image_path('elephant.jpeg') %>"  style="border-radius: 50%; height: 55%; width: 44%" />

        <p class="card-text">Prativa</p>
        
        <br>
      </div>
    </div>
    <div class="col" style="background: linear-gradient(159deg, rgba(37, 37, 50, 0.98) 0%, rgba(35, 35, 45, 0.98) 100%);">
      <div class="card shadow-sm" style="background: linear-gradient(159deg, rgba(37, 37, 50, 0.98) 0%, rgba(35, 35, 45, 0.98) 100%);">
        <div class="card-body">
          <p class="card-text">Residence: USA</p>
          <p class="card-text">City: Youngstown</p>
          <p class="card-text">State: Ohio</p>
          <br>
          <p>English</p>
          <div class="progress my-3" style="height: 9px">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="height: 9px;"></div>
          </div>
          <p>Hindi</p>
          <div class="progress my-3" style="height: 9px">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <p>Nepali</p>
          <div class="progress my-3" style="height: 9px">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 100%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <div class="my-5">
            <h4> Skills</h4>
            <hr>
            <p>Ruby, ReactJS, Python, HTML/CSS, JavaScript, Jenkins, Codeship, Git, Data Visualization, Data Analysis, R programming </p>
            <br>
          </div>

        </div>
      </div>
    </div>
  </div>
</nav>